name: AmongUS
main: mazgani.amongus.AmongUs
version: 1.0
api-version: 1.13
description: The simple Among US game, just beautifully extended in Minecraft.
softdepend: [HolographicDisplays]
commands:
    amongus: